FROM mcr.microsoft.com/dotnet/sdk:10.0 as builder
WORKDIR /app

COPY . ./

# Restore as distinct layers
RUN dotnet restore src/ProxyManager.Files/ProxyManager.Files.csproj

# Build and publish a release
RUN dotnet publish src/ProxyManager.Files/ProxyManager.Files.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app

COPY --from=builder /app/out .
ENTRYPOINT [ "dotnet", "West94.ProxyManager.Files.dll" ]
