FROM mcr.microsoft.com/dotnet/sdk:10.0 as builder
ENV ASPNETCORE_ENVIRONMENT=Production
ENV ASPNETCORE_HTTP_PORT=8080
ENV DOTNET_USE_POLLING_FILE_WATCHER=1

WORKDIR /app

COPY . ./

# Restore as distinct layers
RUN dotnet restore src/ProxyManager/ProxyManager.csproj

# Build and publish a release
RUN dotnet publish src/ProxyManager/ProxyManager.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app

EXPOSE 8443

COPY --from=builder /app/out .
ENTRYPOINT [ "dotnet", "West94.ProxyManager.dll" ]
