// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using West94.ProxyManager.Infrastructure.Data;

#nullable disable

namespace ProxyManager.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ProxyManagerDbContext))]
    partial class ProxyManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("West94.ProxyManager.Core.AggregatesModel.AuditLogAggregate.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_id");

                    b.Property<string>("NewState")
                        .HasColumnType("text")
                        .HasColumnName("new_state");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int>("Operation")
                        .HasColumnType("integer")
                        .HasColumnName("operation");

                    b.Property<string>("PreviousState")
                        .HasColumnType("text")
                        .HasColumnName("previous_state");

                    b.Property<Guid>("ProxyHostId")
                        .HasColumnType("uuid")
                        .HasColumnName("proxy_host_id");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_log_occurred_at");

                    b.ToTable("audit_log_entries", (string)null);
                });

            modelBuilder.Entity("West94.ProxyManager.Infrastructure.Data.CertificateRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CertificateAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("certificate_asset_id");

                    b.Property<string>("CertificateFileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("certificate_file_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Format")
                        .HasColumnType("integer")
                        .HasColumnName("format");

                    b.Property<Guid?>("KeyAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("key_asset_id");

                    b.Property<string>("KeyFileName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("key_file_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("NotAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_after");

                    b.Property<DateTimeOffset>("NotBefore")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_before");

                    b.Property<string>("PassPhrase")
                        .HasColumnType("text")
                        .HasColumnName("pass_phrase");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.PrimitiveCollection<string>("SubjectAlternativeNames")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("subject_alternative_names");

                    b.Property<string>("Thumbprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("thumbprint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("certificates", (string)null);
                });

            modelBuilder.Entity("West94.ProxyManager.Infrastructure.Data.ProxyHostRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CertificateId")
                        .HasColumnType("uuid")
                        .HasColumnName("certificate_id");

                    b.Property<string>("DestinationHost")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("destination_host");

                    b.Property<int>("DestinationPort")
                        .HasColumnType("integer")
                        .HasColumnName("destination_port");

                    b.Property<string>("DestinationScheme")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("destination_scheme");

                    b.PrimitiveCollection<List<string>>("DomainNames")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("domain_names");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.HasKey("Id");

                    b.ToTable("proxy_hosts", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
