// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using West94.ProxyManager.Infrastructure.Data;

#nullable disable

namespace ProxyManager.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ProxyManagerDbContext))]
    partial class ProxyManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("West94.ProxyManager.Core.AggregatesModel.AuditLogAggregate.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_id");

                    b.Property<string>("NewState")
                        .HasColumnType("text")
                        .HasColumnName("new_state");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int>("Operation")
                        .HasColumnType("integer")
                        .HasColumnName("operation");

                    b.Property<string>("PreviousState")
                        .HasColumnType("text")
                        .HasColumnName("previous_state");

                    b.Property<Guid>("ProxyHostId")
                        .HasColumnType("uuid")
                        .HasColumnName("proxy_host_id");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_log_occurred_at");

                    b.ToTable("audit_log_entries", (string)null);
                });

            modelBuilder.Entity("West94.ProxyManager.Infrastructure.Data.ProxyHostRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CertificateKeyPath")
                        .HasColumnType("text")
                        .HasColumnName("certificate_key_path");

                    b.Property<string>("CertificatePassword")
                        .HasColumnType("text")
                        .HasColumnName("certificate_password");

                    b.Property<string>("CertificatePath")
                        .HasColumnType("text")
                        .HasColumnName("certificate_path");

                    b.Property<string>("DestinationHost")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("destination_host");

                    b.Property<int>("DestinationPort")
                        .HasColumnType("integer")
                        .HasColumnName("destination_port");

                    b.Property<string>("DestinationScheme")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("destination_scheme");

                    b.PrimitiveCollection<List<string>>("DomainNames")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("domain_names");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.HasKey("Id");

                    b.ToTable("proxy_hosts", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
