FROM mcr.microsoft.com/dotnet/sdk:10.0 as builder
WORKDIR /app

COPY . ./

# Restore as distinct layers
RUN dotnet restore

# Build and publish a release
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app

COPY --from=builder /app/out .
ENTRYPOINT [ "dotnet", "West94.ProxyManager.API.dll" ]
